refactor: changing the project structure for the kmp branch
CodandoTV/StreamPlayerApp pull request #92
Opened 2024-01-09 23:03 UTC by git-jr

## Descrição

Separação da estrutura do projeto de acordo com as conversas que tivemos

## Testes Realizados

[Descreva os testes que você realizou para verificar a validade das alterações.]

## Screenshots

[Adicione screenshots relevantes, se aplicável.]

## Checklist

- [x] Os testes foram executados e passaram com sucesso.
- [x] As alterações de código seguem as diretrizes de estilo do projeto.
- [ ] Foram adicionados testes, se aplicável.
- [x] Se inscreveu no canal?😛

## Issues Relacionadas

[Adicione as issues relacionadas a esse PR, se houver.]
Wizard de repositório KMP #82

2024-01-10 11:53 UTC, gabrielbmoro approved these changes
@git-jr , fera demais!! Tá approved! 💯 🔥 

Acho que o que está faltando seria só uma seção no README.md principal dizendo que o projeto tem dois projects, um android nativo com o link da pasta e o outro KMP com o link da pasta. Pode ser uma seção bem no início pra direcionar o pessoal melhor.

Cc: @rviannaoliveira

2024-01-11 02:50 UTC, gabrielbmoro approved these changes
Topzera 🔝 zera!!! 🔥 🔥 🔥

2024-01-11 02:50 UTC, gabrielbmoro commented on README.md
> +Este repositório contém dois projetos principais:
❤️

2024-01-14 22:24 UTC, rviannaoliveira requested changes
blocking to merge at the right time

2024-04-01 10:37 UTC, closed without merging